package rpcproto

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Allocation) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "destination":
			z.Destination, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Destination")
				return
			}
		case "amount":
			z.Amount, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		case "allocation_type":
			z.AllocationType, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "AllocationType")
				return
			}
		case "metadata":
			z.Metadata, err = dc.ReadBytes(z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Allocation) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "destination"
	err = en.Append(0x84, 0xab, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Destination)
	if err != nil {
		err = msgp.WrapError(err, "Destination")
		return
	}
	// write "amount"
	err = en.Append(0xa6, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Amount)
	if err != nil {
		err = msgp.WrapError(err, "Amount")
		return
	}
	// write "allocation_type"
	err = en.Append(0xaf, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.AllocationType)
	if err != nil {
		err = msgp.WrapError(err, "AllocationType")
		return
	}
	// write "metadata"
	err = en.Append(0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Metadata)
	if err != nil {
		err = msgp.WrapError(err, "Metadata")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Allocation) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "destination"
	o = append(o, 0x84, 0xab, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Destination)
	// string "amount"
	o = append(o, 0xa6, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Amount)
	// string "allocation_type"
	o = append(o, 0xaf, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendUint8(o, z.AllocationType)
	// string "metadata"
	o = append(o, 0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Metadata)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Allocation) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "destination":
			z.Destination, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Destination")
				return
			}
		case "amount":
			z.Amount, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		case "allocation_type":
			z.AllocationType, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AllocationType")
				return
			}
		case "metadata":
			z.Metadata, bts, err = msgp.ReadBytesBytes(bts, z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Allocation) Msgsize() (s int) {
	s = 1 + 12 + msgp.StringPrefixSize + len(z.Destination) + 7 + msgp.StringPrefixSize + len(z.Amount) + 16 + msgp.Uint8Size + 9 + msgp.BytesPrefixSize + len(z.Metadata)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SingleAssetExit) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "asset":
			z.Asset, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Asset")
				return
			}
		case "metadata":
			z.Metadata, err = dc.ReadBytes(z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		case "allocations":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Allocations")
				return
			}
			if cap(z.Allocations) >= int(zb0002) {
				z.Allocations = (z.Allocations)[:zb0002]
			} else {
				z.Allocations = make([]Allocation, zb0002)
			}
			for za0001 := range z.Allocations {
				err = z.Allocations[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Allocations", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SingleAssetExit) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "asset"
	err = en.Append(0x83, 0xa5, 0x61, 0x73, 0x73, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Asset)
	if err != nil {
		err = msgp.WrapError(err, "Asset")
		return
	}
	// write "metadata"
	err = en.Append(0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Metadata)
	if err != nil {
		err = msgp.WrapError(err, "Metadata")
		return
	}
	// write "allocations"
	err = en.Append(0xab, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Allocations)))
	if err != nil {
		err = msgp.WrapError(err, "Allocations")
		return
	}
	for za0001 := range z.Allocations {
		err = z.Allocations[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Allocations", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SingleAssetExit) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "asset"
	o = append(o, 0x83, 0xa5, 0x61, 0x73, 0x73, 0x65, 0x74)
	o = msgp.AppendString(o, z.Asset)
	// string "metadata"
	o = append(o, 0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Metadata)
	// string "allocations"
	o = append(o, 0xab, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Allocations)))
	for za0001 := range z.Allocations {
		o, err = z.Allocations[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Allocations", za0001)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SingleAssetExit) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "asset":
			z.Asset, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Asset")
				return
			}
		case "metadata":
			z.Metadata, bts, err = msgp.ReadBytesBytes(bts, z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		case "allocations":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Allocations")
				return
			}
			if cap(z.Allocations) >= int(zb0002) {
				z.Allocations = (z.Allocations)[:zb0002]
			} else {
				z.Allocations = make([]Allocation, zb0002)
			}
			for za0001 := range z.Allocations {
				bts, err = z.Allocations[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Allocations", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SingleAssetExit) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Asset) + 9 + msgp.BytesPrefixSize + len(z.Metadata) + 12 + msgp.ArrayHeaderSize
	for za0001 := range z.Allocations {
		s += z.Allocations[za0001].Msgsize()
	}
	return
}
