package rpcproto

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Allocation) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "destination":
			z.Destination, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Destination")
				return
			}
		case "amount":
			z.Amount, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		case "allocation_type":
			z.AllocationType, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "AllocationType")
				return
			}
		case "metadata":
			z.Metadata, err = dc.ReadBytes(z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Allocation) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "destination"
	err = en.Append(0x84, 0xab, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Destination)
	if err != nil {
		err = msgp.WrapError(err, "Destination")
		return
	}
	// write "amount"
	err = en.Append(0xa6, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Amount)
	if err != nil {
		err = msgp.WrapError(err, "Amount")
		return
	}
	// write "allocation_type"
	err = en.Append(0xaf, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.AllocationType)
	if err != nil {
		err = msgp.WrapError(err, "AllocationType")
		return
	}
	// write "metadata"
	err = en.Append(0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Metadata)
	if err != nil {
		err = msgp.WrapError(err, "Metadata")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Allocation) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "destination"
	o = append(o, 0x84, 0xab, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Destination)
	// string "amount"
	o = append(o, 0xa6, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Amount)
	// string "allocation_type"
	o = append(o, 0xaf, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendUint8(o, z.AllocationType)
	// string "metadata"
	o = append(o, 0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Metadata)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Allocation) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "destination":
			z.Destination, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Destination")
				return
			}
		case "amount":
			z.Amount, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		case "allocation_type":
			z.AllocationType, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AllocationType")
				return
			}
		case "metadata":
			z.Metadata, bts, err = msgp.ReadBytesBytes(bts, z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Allocation) Msgsize() (s int) {
	s = 1 + 12 + msgp.StringPrefixSize + len(z.Destination) + 7 + msgp.StringPrefixSize + len(z.Amount) + 16 + msgp.Uint8Size + 9 + msgp.BytesPrefixSize + len(z.Metadata)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *DirectFundRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "counter_party":
			z.CounterParty, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CounterParty")
				return
			}
		case "challenge_duration":
			z.ChallengeDuration, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ChallengeDuration")
				return
			}
		case "outcome":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Outcome")
				return
			}
			if cap(z.Outcome) >= int(zb0002) {
				z.Outcome = (z.Outcome)[:zb0002]
			} else {
				z.Outcome = make([]SingleAssetExit, zb0002)
			}
			for za0001 := range z.Outcome {
				err = z.Outcome[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Outcome", za0001)
					return
				}
			}
		case "app_definition":
			z.AppDefinition, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AppDefinition")
				return
			}
		case "app_data":
			z.AppData, err = dc.ReadBytes(z.AppData)
			if err != nil {
				err = msgp.WrapError(err, "AppData")
				return
			}
		case "nonce":
			z.Nonce, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Nonce")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DirectFundRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "counter_party"
	err = en.Append(0x86, 0xad, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.CounterParty)
	if err != nil {
		err = msgp.WrapError(err, "CounterParty")
		return
	}
	// write "challenge_duration"
	err = en.Append(0xb2, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ChallengeDuration)
	if err != nil {
		err = msgp.WrapError(err, "ChallengeDuration")
		return
	}
	// write "outcome"
	err = en.Append(0xa7, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Outcome)))
	if err != nil {
		err = msgp.WrapError(err, "Outcome")
		return
	}
	for za0001 := range z.Outcome {
		err = z.Outcome[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Outcome", za0001)
			return
		}
	}
	// write "app_definition"
	err = en.Append(0xae, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.AppDefinition)
	if err != nil {
		err = msgp.WrapError(err, "AppDefinition")
		return
	}
	// write "app_data"
	err = en.Append(0xa8, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.AppData)
	if err != nil {
		err = msgp.WrapError(err, "AppData")
		return
	}
	// write "nonce"
	err = en.Append(0xa5, 0x6e, 0x6f, 0x6e, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Nonce)
	if err != nil {
		err = msgp.WrapError(err, "Nonce")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DirectFundRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "counter_party"
	o = append(o, 0x86, 0xad, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79)
	o = msgp.AppendString(o, z.CounterParty)
	// string "challenge_duration"
	o = append(o, 0xb2, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendUint32(o, z.ChallengeDuration)
	// string "outcome"
	o = append(o, 0xa7, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Outcome)))
	for za0001 := range z.Outcome {
		o, err = z.Outcome[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Outcome", za0001)
			return
		}
	}
	// string "app_definition"
	o = append(o, 0xae, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.AppDefinition)
	// string "app_data"
	o = append(o, 0xa8, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.AppData)
	// string "nonce"
	o = append(o, 0xa5, 0x6e, 0x6f, 0x6e, 0x63, 0x65)
	o = msgp.AppendUint64(o, z.Nonce)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DirectFundRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "counter_party":
			z.CounterParty, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CounterParty")
				return
			}
		case "challenge_duration":
			z.ChallengeDuration, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ChallengeDuration")
				return
			}
		case "outcome":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Outcome")
				return
			}
			if cap(z.Outcome) >= int(zb0002) {
				z.Outcome = (z.Outcome)[:zb0002]
			} else {
				z.Outcome = make([]SingleAssetExit, zb0002)
			}
			for za0001 := range z.Outcome {
				bts, err = z.Outcome[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Outcome", za0001)
					return
				}
			}
		case "app_definition":
			z.AppDefinition, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AppDefinition")
				return
			}
		case "app_data":
			z.AppData, bts, err = msgp.ReadBytesBytes(bts, z.AppData)
			if err != nil {
				err = msgp.WrapError(err, "AppData")
				return
			}
		case "nonce":
			z.Nonce, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nonce")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DirectFundRequest) Msgsize() (s int) {
	s = 1 + 14 + msgp.StringPrefixSize + len(z.CounterParty) + 19 + msgp.Uint32Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Outcome {
		s += z.Outcome[za0001].Msgsize()
	}
	s += 15 + msgp.StringPrefixSize + len(z.AppDefinition) + 9 + msgp.BytesPrefixSize + len(z.AppData) + 6 + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *DirectFundResponse) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.Id, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "channel_id":
			z.ChannelId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ChannelId")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z DirectFundResponse) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "id"
	err = en.Append(0x82, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "channel_id"
	err = en.Append(0xaa, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ChannelId)
	if err != nil {
		err = msgp.WrapError(err, "ChannelId")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z DirectFundResponse) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "id"
	o = append(o, 0x82, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.Id)
	// string "channel_id"
	o = append(o, 0xaa, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ChannelId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DirectFundResponse) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.Id, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "channel_id":
			z.ChannelId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ChannelId")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z DirectFundResponse) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.Id) + 11 + msgp.StringPrefixSize + len(z.ChannelId)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SingleAssetExit) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "asset":
			z.Asset, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Asset")
				return
			}
		case "metadata":
			z.Metadata, err = dc.ReadBytes(z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		case "allocations":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Allocations")
				return
			}
			if cap(z.Allocations) >= int(zb0002) {
				z.Allocations = (z.Allocations)[:zb0002]
			} else {
				z.Allocations = make([]Allocation, zb0002)
			}
			for za0001 := range z.Allocations {
				err = z.Allocations[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Allocations", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SingleAssetExit) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "asset"
	err = en.Append(0x83, 0xa5, 0x61, 0x73, 0x73, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Asset)
	if err != nil {
		err = msgp.WrapError(err, "Asset")
		return
	}
	// write "metadata"
	err = en.Append(0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Metadata)
	if err != nil {
		err = msgp.WrapError(err, "Metadata")
		return
	}
	// write "allocations"
	err = en.Append(0xab, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Allocations)))
	if err != nil {
		err = msgp.WrapError(err, "Allocations")
		return
	}
	for za0001 := range z.Allocations {
		err = z.Allocations[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Allocations", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SingleAssetExit) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "asset"
	o = append(o, 0x83, 0xa5, 0x61, 0x73, 0x73, 0x65, 0x74)
	o = msgp.AppendString(o, z.Asset)
	// string "metadata"
	o = append(o, 0xa8, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Metadata)
	// string "allocations"
	o = append(o, 0xab, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Allocations)))
	for za0001 := range z.Allocations {
		o, err = z.Allocations[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Allocations", za0001)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SingleAssetExit) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "asset":
			z.Asset, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Asset")
				return
			}
		case "metadata":
			z.Metadata, bts, err = msgp.ReadBytesBytes(bts, z.Metadata)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
		case "allocations":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Allocations")
				return
			}
			if cap(z.Allocations) >= int(zb0002) {
				z.Allocations = (z.Allocations)[:zb0002]
			} else {
				z.Allocations = make([]Allocation, zb0002)
			}
			for za0001 := range z.Allocations {
				bts, err = z.Allocations[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Allocations", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SingleAssetExit) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Asset) + 9 + msgp.BytesPrefixSize + len(z.Metadata) + 12 + msgp.ArrayHeaderSize
	for za0001 := range z.Allocations {
		s += z.Allocations[za0001].Msgsize()
	}
	return
}
